### ISSUE TITLE
build for a specific tcl installation

### ISSUE THREAD

**Issue by rihabesx** [nukedzn/node-tcl#11]
Hi,
It is mentioned in the readme
"The build process will look for  tclConfig.sh  to identify Tcl include directory and linker flags. If you are using a Tcl version older than 8.5 or want to link to a specific Tcl installation use the  TCLCONFIG  environment variable to override the default behaviour (e.g.  export TCLCONFIG=/path/to/tclConfig.sh )."

how do I create the build to point to a specifc tclsh installation?

**Comment by uditha-atukorala** [comment]
Hi, 

It is exactly as it says in the readme, if you want to build against a specific tcl installation set the `TCLCONFIG` environment variable to point to the `tclConfig.sh` of that specific installation (e.g. `export TCLCONFIG=/usr/lib/tcl8.6/tclConfig.sh`). 

Or, if you are using Tcl 8.5 or newer and the default `tclsh` is pointing to the specific installation you want then that's all you have to do.

**Comment by uditha-atukorala** [comment]
@rihabesx Did my comment answer your question?

**Comment by rihabesx** [comment]
Yes thanks.
